### ISSUE TITLE
Feature: Workout Tracker Module

### ISSUE THREAD

**Issue by pluciuspua** [lambraydon/GymBros#3]
Develop Workout Tracker Module: 

1. Takes in User Input (Exercise Name, Weight, Sets, Reps etc. )
2. Saves information in FireStore such that it can be accessed later -> Workout Data can be created in FireStore
3. Workout information can be extracted and read from FireStore -> Workout Data can be extracted from FireStore (access via homepage)

**Comment by lambraydon** [comment]
Feature has been implemented
